name: bmi_calculator
description: "A new Flutter project."


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0-42.2.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0





flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Libre
      fonts:
        - asset: assets\fonts\LibreBaskerville-Regular.ttf
        - asset: assets\fonts\LibreBaskerville-Italic.ttf
        - asset: assets\fonts\LibreBaskerville-Bold.ttf

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
